apiVersion: v1
kind: ConfigMap
metadata:
  name: lab2-config
data:
  GREETING: Bambaleilo
---
apiVersion: v1
kind: Secret
metadata:
  name: lab2-secret 
type: Opaque
data:
  DATABASE_URI: cG9zdGdyZXNxbCtwc3ljb3BnMjovL215dXNlcjpwYXNzd2RAcG9zdGdyZXM6NTQzMi9teWFwcA==      