replicaCount: 2

image:
  repository: student12345/lab2_1-py
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/otusapp"]


postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    type: NodePort
    nodePort: "31721"
    port: "5432"
