apiVersion: v1
name: chart
description: A Helm chart for Kubernetes

type: application

version: 0.4.0
appVersion: 0.4.0.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - lab3-database