{
 "title": "Lab3_Grafana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (method, le, uri) (rate(app_request_latency_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.5 {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency 0.9",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (method, le, uri) (rate(app_request_latency_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.9 {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (method, le, uri) (rate(app_request_latency_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Max {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (method, le, uri) (rate(app_request_latency_seconds_bucket[1m]))) * 1000",
     "legendFormat": " 0.99 {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status) (rate(app_request_count_total{http_status=~\"5..\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(app_request_latency_seconds_count[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Nginx Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (ingress, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'lab3-chart.*'}[1m]))) * 1000",
     "legendFormat": "0.5 {{ingress}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (ingress, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'lab3-chart.*'}[1m]))) * 1000",
     "legendFormat": "0.95 {{ingress}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (ingress, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'lab3-chart.*'}[1m]))) * 1000",
     "legendFormat": "0.99 {{ingress}}"
    },
    {
     "expr": "histogram_quantile(1, sum by (ingress, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'lab3-chart.*'}[1m]))) * 1000",
     "legendFormat": "Max {{ingress}}"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ingress) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'lab3-chart.*', status=~\"5..\"}[1m]))",
     "legendFormat": "{{ingress}} 5xx"
    }
   ]
  },
  {
   "title": "App Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"chart\", pod=~'lab3-.*'}",
     "legendFormat": "Pod {{pod}}"
    }
   ]
  },
  {
   "title": "App CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_user_seconds_total{container=\"chart\", pod=~\"lab3-.*\"}[30s])) without (cpu) * 100",
     "legendFormat": "Pod {{pod}}"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ingress) (rate(nginx_ingress_controller_request_duration_seconds_count{ingress=~'lab3-chart.*'}[1m]))",
     "legendFormat": "{{ingress}}"
    }
   ]
  }
 ]
}